global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'broker'
    static_configs:
      - targets: ['broker:8080']
  - job_name: 'ml-processor'
    static_configs:
      - targets: ['ml-processor:5000']
